"""
Author's Note:

This is a custom Python script used to convert copied text data from the website oryzasnp.org into a table of records containing the rice's phenotype data. The data was obtained by manually perusing the database and copy-pasting the shown values.

This script was made in part of my 3+1 Research project, to make a classifier using Indonesian rice phenotype data.

This script assumes all acquired data are in the form of a loooooooooooong vertical list, and then stores the end product in CSV format.

This script is the frontend script. Run this one.
The backend script is convert.py.

This script has predefined variables, denoted by the comment (# PREDEFINED).
Change those to "" (blank) for string or 0 for int, or other values if you're going to use it for different data.
If you change them to "" or 0, you will be asked for input each time you run this script.

(kurisu_na, 7-10 March 2016, final revision on 8 April 2016.)
"""

# Import the backend script, convert.py.
import convert

# And now, let's clear the clutter.
import os
os.system("cls" if os.name == "nt" else "clear")

""" PARAMETERS """
# Part 1 parameter definitions.
filename_open = "indonesian_rice.txt" # PREDEFINED string
filename_save = "indonesian_rice_table.csv" # PREDEFINED string
tcol_count = 0 # total column count, will be 2 if no description column and 3 if there is one.
variety_separator = "END" # PREDEFINED string
eof_mark = "EOF" # PREDEFINED string

# Part 2 and 3 parameter definitions.
field_name_index = 0
field_desc_index = 1 # PREDEFINED int
value_index = 3 # PREDEFINED int

""" DATA VARIABLES """
# Stores the entire record list.
data = []

# Stores the list of field names only, since Part 3 won't be using field name descriptions.
field_names_list = []


""" Frontend Start """

# Welcome speech! Of sorts.
print("Hello!\n\n")
print("Before we start, make sure that:\n")
print("1. The file containing the data you want to convert into a table is in the \"Files\"")
print("   folder. The script will automatically find it.\n")
print("2. You have the script \"makeCSV.py\" in the same folder as this script.")
print("3. The initial data is in the form of a very long vertical list.\n")
print("4. You have put a separator cue for each variety.\n")
print("5. You have put an EOF cue in the very last line of the file.\n\n")

print("All files generated by this script will be stored in the \"Files\" folder.\n\n")

while filename_open == "":
    filename_open = input("Enter the file name to OPEN (with extension): ")

while filename_save == "":
    filename_save = input("Enter the file name to SAVE in (with extension, CSV recommended): ")

while tcol_count == 0:
    field_desc_index = int(input("Column no. of FIELD NAME DESCRIPTION in each row copied [0..2], 0 if no description): "))
    value_index = int(input("Column no. of FIELD VALUE in each row copied [1..3]: "))

    if field_desc_index == 0: # col1, col2 only
        tcol_count = 2
        if value_index == 1:
            field_name_index = 2
        else:
            field_name_index = 1
    else:
        tcol_count = 3
        if field_desc_index == 1: # col2, col3 left
            if value_index == 2:
                field_name_index = 3
            else:
                field_name_index = 2
        else: # col1, col3 left
            if value_index == 1:
                field_name_index = 3
            else:
                field_name_index = 1

while variety_separator == "":
    variety_separator = input("Enter VARIETY SEPARATOR cue: ") # END

while eof_mark == "":
    eof_mark = input("Enter file's EOF CUE: ") #EOF

print("\n\n  Shifting gears...")
print("  Thinking...")
print("  Converting data...")


""" Script magic at work here. """

# Run Part 1 of convert.py.
convert.mkRecordList(data, filename_open, tcol_count, variety_separator, eof_mark)

# Run Part 2 and 3 of convert.py.
convert.mkTableHeaders(data, filename_save, field_name_index, field_desc_index, field_names_list)
convert.mkTable(data, filename_save, field_name_index, value_index, field_names_list)

""" All done!"""

print("\n\nConversion successful!")
print("Check the \"Files\" folder for your file.\n\n")
input("Press Enter to exit script.")
